import { act, fireEvent, render, screen } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import StepEmployeeInfo from '../StepEmployeeInfo'
import StepIdentity from '../StepIdentity'
import StepJob from '../StepJob'
import ClusterReview from '../../clusters/ClusterReview'
import { useHireWizard } from '@/lib/admin/store/useHireWizard'

const messages: Record<string, string> = {
  // identity
  hireDate: 'วันเริ่มงาน',
  company: 'บริษัท',
  eventReason: 'เหตุผล',
  salutationEn: 'คำนำหน้า (EN)',
  firstNameEn: 'ชื่อ (EN)',
  middleNameEn: 'ชื่อกลาง',
  lastNameEn: 'นามสกุล (EN)',
  dateOfBirth: 'วันเกิด',
  countryOfBirth: 'ประเทศที่เกิด',
  regionOfBirth: 'จังหวัด/ภูมิภาคที่เกิด',
  employeeId: 'รหัสพนักงาน',
  employeeIdAutoGenerated: 'ระบบสร้างอัตโนมัติ',
  salutationLocal: 'คำนำหน้า (ภาษาท้องถิ่น)',
  nationalIdCardType: 'ประเภทบัตร',
  country: 'ประเทศ',
  nationalId: 'เลขบัตร',
  issueDate: 'วันออกบัตร',
  expiryDate: 'วันหมดอายุ',
  isPrimary: 'บัตรหลัก',
  selectCompanyPlaceholder: '— เลือกบริษัท —',
  selectEventReasonPlaceholder: '— เลือกสาเหตุ —',
  selectSalutationPlaceholder: '— เลือกคำนำหน้า —',
  selectCountryPlaceholder: '— เลือกประเทศ (optional) —',
  selectCountryRequiredPlaceholder: '— เลือกประเทศ —',
  selectCardTypePlaceholder: '— เลือกประเภทบัตร —',
  selectPlaceholder: '— เลือก —',
  firstNameEnPlaceholder: 'ชื่อ ภาษาอังกฤษ',
  middleNameEnPlaceholder: 'ชื่อกลาง ภาษาอังกฤษ — ไม่บังคับ',
  lastNameEnPlaceholder: 'นามสกุล ภาษาอังกฤษ',
  nationalIdPlaceholder: 'เลขบัตรประชาชน / Passport / เลขอื่นๆ',
  regionOfBirthPlaceholder: 'จังหวัด/ภูมิภาค (optional)',
  ageLabel: 'อายุ',
  ageUnit: 'ปี',
  requiredHint: 'ช่องที่บังคับกรอก',
  isPrimaryHint: 'บัตรหลัก = เอกสารยืนยันตัวตนหลัก',
  nationalIdChecksumError: 'เลขบัตรประชาชนไม่ถูกต้อง',
  forwardDateWarning: 'วันที่เริ่มงานล่วงหน้าต้องผ่านการอนุมัติจาก SPD ก่อนเปิดใช้งาน',
  // employee info
  employeeGroup: 'Employee Group',
  employeeSubGroup: 'Employee Sub-Group',
  selectEmployeeGroup: 'Select employee group',
  selectEmployeeSubGroup: 'Select employee sub-group',
  employeeGroupHelp: 'Payroll classification',
  employeeSubGroupHelp: 'Payroll classification subgroup',
  employmentDetails: 'Employment Details',
  originalStartDate: 'Original Start Date',
  seniorityStartDate: 'Seniority Start Date',
  retirementDate: 'Retirement Date',
  retirementDateHint: 'calculated from DOB',
  pfServiceDate: 'PVD Entry Date',
  dvtPreviousId: 'Previous Employee ID (DVT)',
  cgPreviousEmployeeId: 'Previous CG Employee ID',
  ssn: 'SSN / National ID',
  ssnHint: '(for SSO)',
  ssnPlaceholder: '13 digits',
  idPlaceholder: 'Employee ID',
  ageDisplay: 'Age',
  ageHint: 'from date of birth',
  // job
  position: 'Position',
  positionHelp: 'Derived from selected Position',
  workLocation: 'Store-Branch Code (from Position)',
  hrDistrict: 'HR District',
  jobOrgSection: 'Job Organisation',
  department: 'Department',
  division: 'Division',
  costCenter: 'Cost Center',
  jobFunction: 'Job Function',
  corporateTitle: 'Corporate Title',
  timeInfoSection: 'Time Information',
  // review
  enNameSectionTitle: 'ชื่อ-นามสกุลภาษาอังกฤษ',
  enNameSectionSub: 'คัดลอกจากขั้นตอนระบุตัวตน',
  hrbpSectionTitle: 'HRBP Manager',
  hrbpSectionSub: 'เลือก HRBP ที่จะรับเรื่องและแจ้งเตือนเมื่อส่งข้อมูล',
  salutationEnReview: 'คำนำหน้า (EN)',
  firstNameEnReview: 'ชื่อ (EN)',
  middleNameEnReview: 'ชื่อกลาง (EN)',
  lastNameEnReview: 'นามสกุล (EN)',
  hrbpAssignee: 'Assigned HRBP',
  selectHrbp: '— Select HRBP —',
  notifyHrbpLabel: 'Notify HRBP via email when submitted',
  notifyHrbpHelp: 'Email notification intent',
  salarySuffix: 'บาท/เดือน',
  summarySectionTitle: 'สรุปข้อมูลก่อนส่ง',
  summarySectionSub: 'ตรวจสอบก่อนบันทึก',
  summaryHireDate: 'วันที่เริ่มงาน',
  summaryCompany: 'บริษัท',
  summaryEventReason: 'สาเหตุการจ้าง',
  summarySalutationEn: 'คำนำหน้า (EN)',
  summaryNameEn: 'ชื่อ-นามสกุล (EN)',
  summaryDateOfBirth: 'วันเกิด',
  summaryEmployeeId: 'รหัสพนักงาน (ระบบสร้าง)',
  summaryIdCardType: 'ประเภทบัตร',
  summaryIdNumber: 'เลขบัตร',
  summaryCountry: 'ประเทศ',
  summaryIsPrimary: 'บัตรหลัก',
  summarySalutationLocal: 'คำนำหน้า (Local)',
  summaryNameLocal: 'ชื่อ-นามสกุล (Local)',
  summaryNickname: 'ชื่อเล่น',
  summaryGender: 'เพศ',
  summaryNationality: 'สัญชาติ',
  summaryBloodType: 'กรุ๊ปเลือด',
  summaryMaritalStatus: 'สถานภาพสมรส',
  summaryEmployeeClass: 'ประเภทพนักงาน',
  summaryPosition: 'ตำแหน่ง',
  summaryCompensation: 'ค่าตอบแทน',
  summaryHrbp: 'HRBP ที่มอบหมาย',
  summaryNotSelected: '— ยังไม่เลือก —',
}

vi.mock('next-intl', () => ({
  useTranslations: () => (key: string) => messages[key] ?? key,
}))

vi.mock('@/components/admin/PositionLookup', () => ({
  default: () => <div>Position lookup</div>,
}))

beforeEach(() => {
  localStorage.clear()
  act(() => {
    useHireWizard.getState().reset()
  })
})

describe('MS Teams hiring feedback regression', () => {
  it('surfaces the generated employee ID in the Step 1 identity area', () => {
    render(<StepIdentity />)

    expect(screen.getByText('รหัสพนักงาน')).toBeInTheDocument()
    expect(screen.getByText(/ระบบสร้างอัตโนมัติ/)).toBeInTheDocument()
    expect(screen.getByLabelText('รหัสพนักงาน')).toHaveTextContent(/EMP-/)
  })

  it('does not render removed employment-detail fields from the Teams feedback', () => {
    render(<StepEmployeeInfo />)

    expect(screen.queryByLabelText('Previous Employee ID (DVT)')).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/SSN \/ National ID/)).not.toBeInTheDocument()
    expect(screen.queryByLabelText('PVD Entry Date')).not.toBeInTheDocument()
  })

  it('keeps HRBP assignment and email-notification intent in the review area', () => {
    render(<ClusterReview />)

    expect(screen.getByRole('heading', { name: 'HRBP Manager' })).toBeInTheDocument()
    expect(screen.getByLabelText(/Assigned HRBP/)).toBeInTheDocument()
    expect(screen.getByLabelText('Notify HRBP via email when submitted')).toBeChecked()
  })

  it('keeps the compensation organisation pay scale group visible when advanced job fields are opened', () => {
    render(<StepJob />)

    fireEvent.click(screen.getByRole('button', { name: /Pay Scale, Time, FTE/ }))

    expect(screen.getByText('Compensation Organisation / โครงสร้างเงินเดือน')).toBeInTheDocument()
    expect(screen.getByLabelText(/Pay Scale Type/)).toBeInTheDocument()
    expect(screen.getByLabelText(/Pay Scale Area/)).toBeInTheDocument()
    expect(screen.getByLabelText(/Pay Scale Group/)).toBeInTheDocument()
    expect(screen.getByLabelText(/Pay Scale Level/)).toBeInTheDocument()
  })
})
