import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import StepEmployeeInfo from '../StepEmployeeInfo'
import StepIdentity from '../StepIdentity'
import StepJob from '../StepJob'
import ClusterReview from '../../clusters/ClusterReview'
import { useHireWizard } from '@/lib/admin/store/useHireWizard'

const messages: Record<string, string> = {
  // identity
  hireDate: 'วันเริ่มงาน',
  company: 'บริษัท',
  eventReason: 'เหตุผล',
  salutationEn: 'คำนำหน้า (EN)',
  firstNameEn: 'ชื่อ (EN)',
  middleNameEn: 'ชื่อกลาง',
  lastNameEn: 'นามสกุล (EN)',
  dateOfBirth: 'วันเกิด',
  countryOfBirth: 'ประเทศที่เกิด',
  regionOfBirth: 'จังหวัด/ภูมิภาคที่เกิด',
  employeeId: 'รหัสพนักงาน',
  employeeIdAutoGenerated: 'ระบบสร้างอัตโนมัติ',
  dvtPreviousId: 'Previous Employee ID (DVT)',
  dvtPreviousIdPlaceholder: 'Enter if previously an intern/DVT',
  dvtPreviousIdHelp: 'Used to look up previous intern records and prefill matching data when available',
  salutationLocal: 'คำนำหน้า (ภาษาท้องถิ่น)',
  nationalIdCardType: 'ประเภทบัตร',
  country: 'ประเทศ',
  nationalId: 'เลขบัตร',
  issueDate: 'วันออกบัตร',
  expiryDate: 'วันหมดอายุ',
  isPrimary: 'บัตรหลัก',
  selectCompanyPlaceholder: '— เลือกบริษัท —',
  selectEventReasonPlaceholder: '— เลือกสาเหตุ —',
  selectSalutationPlaceholder: '— เลือกคำนำหน้า —',
  selectCountryPlaceholder: '— เลือกประเทศ (optional) —',
  selectCountryRequiredPlaceholder: '— เลือกประเทศ —',
  selectCardTypePlaceholder: '— เลือกประเภทบัตร —',
  selectPlaceholder: '— เลือก —',
  firstNameEnPlaceholder: 'ชื่อ ภาษาอังกฤษ',
  middleNameEnPlaceholder: 'ชื่อกลาง ภาษาอังกฤษ — ไม่บังคับ',
  lastNameEnPlaceholder: 'นามสกุล ภาษาอังกฤษ',
  nationalIdPlaceholder: 'เลขบัตรประชาชน / Passport / เลขอื่นๆ',
  regionOfBirthPlaceholder: 'จังหวัด/ภูมิภาค (optional)',
  ageLabel: 'อายุ',
  ageUnit: 'ปี',
  requiredHint: 'ช่องที่บังคับกรอก',
  isPrimaryHint: 'บัตรหลัก = เอกสารยืนยันตัวตนหลัก',
  nationalIdChecksumError: 'เลขบัตรประชาชนไม่ถูกต้อง',
  forwardDateWarning: 'วันที่เริ่มงานล่วงหน้าต้องผ่านการอนุมัติจาก SPD ก่อนเปิดใช้งาน',
  // employee info
  employeeGroup: 'Employee Group',
  employeeSubGroup: 'Employee Sub-Group',
  selectEmployeeGroup: 'Select employee group',
  selectEmployeeSubGroup: 'Select employee sub-group',
  employeeGroupHelp: 'Payroll classification',
  employeeSubGroupHelp: 'Payroll classification subgroup',
  employmentDetails: 'Employment Details',
  originalStartDate: 'Original Start Date',
  seniorityStartDate: 'Seniority Start Date',
  retirementDate: 'Retirement Date',
  retirementDateHint: 'calculated from DOB',
  pfServiceDate: 'PVD Entry Date',
  cgPreviousEmployeeId: 'Previous CG Employee ID',
  ssn: 'SSN / National ID',
  ssnHint: '(for SSO)',
  ssnPlaceholder: '13 digits',
  idPlaceholder: 'Employee ID',
  ageDisplay: 'Age',
  ageHint: 'from date of birth',
  // job
  position: 'Position',
  positionHelp: 'Derived from selected Position',
  workLocation: 'Store-Branch Code (from Position)',
  hrDistrict: 'HR District',
  supervisorId: 'Supervisor ID',
  jobOrgSection: 'Job Organisation',
  department: 'Department',
  division: 'Division',
  costCenter: 'Cost Center',
  jobFunction: 'Job Function',
  corporateTitle: 'Corporate Title',
  timeInfoSection: 'Time Information',
  overrideStandardWeeklyHours: 'Override Standard Weekly Hours',
  dayOffType: 'Day off Type',
  selectDayOffType: '— Select day off type —',
  dayOffFixed: 'Fixed day off',
  dayOffShift: 'Shift-based day off',
  dayOffRotation: 'Rotating day off',
  overrideYes: 'Override',
  overrideNo: 'Use standard',
  // review
  enNameSectionTitle: 'ชื่อ-นามสกุลภาษาอังกฤษ',
  enNameSectionSub: 'คัดลอกจากขั้นตอนระบุตัวตน',
  hrbpSectionTitle: 'Direct Manager Approval + HRBP',
  hrbpSectionSub: 'Direct Manager must approve the hire; notify both Direct Manager and HRBP when submitted',
  directManagerApprover: 'Direct Manager Approver',
  directManagerHelp: 'Auto-filled from the selected Position FO Supervisor ID',
  salutationEnReview: 'คำนำหน้า (EN)',
  firstNameEnReview: 'ชื่อ (EN)',
  middleNameEnReview: 'ชื่อกลาง (EN)',
  lastNameEnReview: 'นามสกุล (EN)',
  hrbpAssignee: 'Assigned HRBP',
  selectHrbp: '— Select HRBP —',
  notifyHrbpLabel: 'Notify both Direct Manager and HRBP via email when submitted',
  notifyHrbpHelp: 'Direct Manager approval is required; HRBP receives the hiring notification',
  salarySuffix: 'บาท/เดือน',
  summarySectionTitle: 'สรุปข้อมูลก่อนส่ง',
  summarySectionSub: 'ตรวจสอบก่อนบันทึก',
  summaryHireDate: 'วันที่เริ่มงาน',
  summaryCompany: 'บริษัท',
  summaryEventReason: 'สาเหตุการจ้าง',
  summarySalutationEn: 'คำนำหน้า (EN)',
  summaryNameEn: 'ชื่อ-นามสกุล (EN)',
  summaryDateOfBirth: 'วันเกิด',
  summaryEmployeeId: 'รหัสพนักงาน (ระบบสร้าง)',
  summaryIdCardType: 'ประเภทบัตร',
  summaryIdNumber: 'เลขบัตร',
  summaryCountry: 'ประเทศ',
  summaryIsPrimary: 'บัตรหลัก',
  summarySalutationLocal: 'คำนำหน้า (Local)',
  summaryNameLocal: 'ชื่อ-นามสกุล (Local)',
  summaryNickname: 'ชื่อเล่น',
  summaryGender: 'เพศ',
  summaryNationality: 'สัญชาติ',
  summaryBloodType: 'กรุ๊ปเลือด',
  summaryMaritalStatus: 'สถานภาพสมรส',
  summaryEmployeeClass: 'ประเภทพนักงาน',
  summaryPosition: 'ตำแหน่ง',
  summaryCompensation: 'ค่าตอบแทน',
  summaryDirectManager: 'Direct Manager Approver',
  summaryHrbp: 'HRBP ที่มอบหมาย',
  summaryNotSelected: '— ยังไม่เลือก —',
}

vi.mock('next-intl', () => ({
  useTranslations: () => (key: string) => messages[key] ?? key,
}))

vi.mock('@/components/admin/PositionLookup', () => ({
  default: ({ onSelect }: { onSelect: (cascade: Record<string, string>) => void }) => (
    <button
      type="button"
      onClick={() => onSelect({
        code: 'POS-00004',
        titleTh: 'พนักงานขายอาวุโส',
        titleEn: 'Senior Sales Associate',
        businessUnit: 'CDS',
        businessUnitLabel: 'Central Department Store',
        branch: 'CDS-CTW',
        branchLabel: 'Central World',
        job: 'RETAIL_OPS',
        jobLabel: 'Retail Operations',
        jobGrade: 'JG-04',
        jobGradeLabel: 'Senior Staff',
        managerPositionCode: '20001001',
        managerPositionLabel: 'Direct Manager from FO',
        hrDistrict: 'D-BKK-1',
      })}
    >
      Position lookup
    </button>
  ),
}))

beforeEach(() => {
  localStorage.clear()
  act(() => {
    useHireWizard.getState().reset()
  })
})

describe('MS Teams hiring feedback regression', () => {
  it('puts DVT previous employee ID first in Step 1 and syncs it for downstream prefill', async () => {
    render(<StepIdentity />)

    const dvtInput = screen.getByLabelText('Previous Employee ID (DVT)')
    const hireDateInput = screen.getByLabelText(/วันเริ่มงาน/)

    expect(
      dvtInput.compareDocumentPosition(hireDateInput) & Node.DOCUMENT_POSITION_FOLLOWING
    ).toBeTruthy()
    expect(screen.getByText('Used to look up previous intern records and prefill matching data when available')).toBeInTheDocument()

    fireEvent.change(dvtInput, { target: { value: 'DVT-2024-0007' } })

    await waitFor(() => {
      expect(useHireWizard.getState().formData.employeeInfo.dvtPreviousId).toBe('DVT-2024-0007')
    })
  })

  it('shows employee ID as generated after submit, not pre-generated in Step 1', () => {
    render(<StepIdentity />)

    expect(screen.getByText('รหัสพนักงาน')).toBeInTheDocument()
    expect(screen.getByText(/ระบบสร้างอัตโนมัติ/)).toBeInTheDocument()
    expect(screen.getByLabelText('รหัสพนักงาน')).toHaveTextContent('สร้างหลัง Submit')
    expect(screen.getByLabelText('รหัสพนักงาน')).not.toHaveTextContent(/EMP-|^2\d{7}$/)
  })

  it('does not render removed employment-detail fields from the Teams feedback', () => {
    render(<StepEmployeeInfo />)

    expect(screen.queryByLabelText('Previous Employee ID (DVT)')).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/SSN \/ National ID/)).not.toBeInTheDocument()
    expect(screen.queryByLabelText('PVD Entry Date')).not.toBeInTheDocument()
  })

  it('validates Employee Info from visible hiring fields without the removed Employee Class UI', async () => {
    const onValidChange = vi.fn()
    render(<StepEmployeeInfo onValidChange={onValidChange} />)

    fireEvent.change(screen.getByLabelText('Employee Group'), { target: { value: '1' } })
    fireEvent.change(screen.getByLabelText('Employee Sub-Group'), { target: { value: 'U0' } })
    fireEvent.change(screen.getByLabelText(/Original Start Date/), { target: { value: '2026-05-10' } })
    fireEvent.change(screen.getByLabelText(/Seniority Start Date/), { target: { value: '2026-05-10' } })

    await waitFor(() => {
      expect(onValidChange).toHaveBeenLastCalledWith(true)
    })
    expect(useHireWizard.getState().formData.employeeInfo.employeeClass).toBeNull()
    expect(useHireWizard.getState().formData.employeeInfo.employeeGroup).toBe('1')
    expect(useHireWizard.getState().formData.employeeInfo.employeeSubGroup).toBe('U0')
  })

  it('shows Direct Manager approval requirement and notifies both Direct Manager and HRBP', () => {
    act(() => {
      const state = useHireWizard.getState()
      useHireWizard.setState({
        formData: {
          ...state.formData,
          job: {
            ...state.formData.job,
            supervisorId: '20001001',
            supervisorLabel: 'Direct Manager from FO',
          },
        },
      })
    })

    render(<ClusterReview />)

    expect(screen.getByRole('heading', { name: 'Direct Manager Approval + HRBP' })).toBeInTheDocument()
    expect(screen.getByText('Direct Manager must approve the hire; notify both Direct Manager and HRBP when submitted')).toBeInTheDocument()
    expect(screen.getByLabelText(/Direct Manager Approver/)).toHaveValue('20001001 — Direct Manager from FO')
    expect(screen.getByLabelText(/Assigned HRBP/)).toBeInTheDocument()
    expect(screen.getByLabelText('Notify both Direct Manager and HRBP via email when submitted')).toBeChecked()
    expect(screen.getByText('Direct Manager approval is required; HRBP receives the hiring notification')).toBeInTheDocument()
  })

  it('auto-fills Supervisor ID from Position FO and exposes requested working-hour fields without Pay Scale', () => {
    render(<StepJob />)

    fireEvent.click(screen.getByRole('button', { name: 'Position lookup' }))

    expect(screen.getByText('Supervisor ID')).toBeInTheDocument()
    expect(screen.getByText(/20001001 — Direct Manager from FO/)).toBeInTheDocument()

    fireEvent.click(screen.getByRole('button', { name: /Time, FTE/ }))

    expect(screen.queryByText('Compensation Organisation / โครงสร้างเงินเดือน')).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/Pay Scale Type/)).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/Pay Scale Area/)).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/Pay Scale Group/)).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/Pay Scale Level/)).not.toBeInTheDocument()
    expect(screen.getByLabelText(/Override Standard Weekly Hours/)).toBeInTheDocument()
    expect(screen.getByLabelText(/Day off Type/)).toBeInTheDocument()
  })
})
