// Mock PendingRequest items for the Unified Approval Workspace (A-4).
// Mixes leave / overtime / claim / transfer types with varied urgency.
// 20 items — enough to exercise filter + pagination UI.

import type {
  PendingRequest,
  LeaveDetails,
  OvertimeDetails,
  ClaimDetails,
  TransferDetails,
} from '@/lib/quick-approve-api';

const leave = (overrides: Partial<LeaveDetails> = {}): LeaveDetails => ({
  leaveType: 'annual',
  startDate: '2026-05-05',
  endDate: '2026-05-07',
  totalDays: 3,
  balance: 10,
  reason: 'พักผ่อนประจำปี',
  ...overrides,
});

const overtime = (overrides: Partial<OvertimeDetails> = {}): OvertimeDetails => ({
  date: '2026-05-03',
  hours: 4,
  rate: 1.5,
  reason: 'งาน production ฉุกเฉิน',
  ...overrides,
});

const claim = (overrides: Partial<ClaimDetails> = {}): ClaimDetails => ({
  amount: 2500,
  currency: 'THB',
  category: 'medical',
  merchant: 'BNH Hospital',
  policyChecks: [
    { rule: 'Within annual limit', passed: true },
    { rule: 'Receipt attached', passed: true },
  ],
  ...overrides,
});

const transfer = (overrides: Partial<TransferDetails> = {}): TransferDetails => ({
  fromDepartment: 'Operations',
  toDepartment: 'Strategy',
  fromPosition: 'Analyst',
  toPosition: 'Senior Analyst',
  reason: 'ขยายบทบาท',
  effectiveDate: '2026-06-01',
  ...overrides,
});

function chain(
  approver1: string,
  approver2?: string,
  approver3?: string,
): PendingRequest['approvalTimeline'] {
  const steps: PendingRequest['approvalTimeline'] = [
    { step: 1, approver: approver1, status: 'approved', date: '2026-04-28' },
  ];
  if (approver2) steps.push({ step: 2, approver: approver2, status: 'pending' });
  if (approver3) steps.push({ step: 3, approver: approver3, status: 'pending' });
  return steps;
}

export const MOCK_PENDING_REQUESTS: PendingRequest[] = [
  {
    id: 'WF-2026-001',
    type: 'leave',
    requester: { id: 'EMP-003', name: 'ณัฐพงษ์ แก้วใส', position: 'Software Engineer', department: 'IT' },
    description: 'ลาพักร้อน 3 วัน — ร่วมงานครอบครัว',
    submittedAt: '2026-04-28T09:30:00',
    urgency: 'urgent',
    waitingDays: 4,
    assignedApprover: { id: 'MGR001', name: 'พิชญ์ ม. (หัวหน้าทีม)', assignedAt: '2026-04-28T10:00:00' },
    details: leave({ startDate: '2026-05-05', endDate: '2026-05-07', totalDays: 3 }),
    approvalTimeline: chain('Manager A', 'HRBP'),
  },
  {
    id: 'WF-2026-002',
    type: 'leave',
    requester: { id: 'EMP-007', name: 'พลอย สุขสวัสดิ์', position: 'UX Designer', department: 'Product' },
    description: 'ลาป่วย 1 วัน — ใบรับรองแพทย์แนบ',
    submittedAt: '2026-04-29T07:45:00',
    urgency: 'urgent',
    waitingDays: 3,
    attachments: ['medical-certificate.pdf'],
    details: leave({ leaveType: 'sick', startDate: '2026-04-30', endDate: '2026-04-30', totalDays: 1, balance: 30 }),
    approvalTimeline: chain('Manager B'),
  },
  {
    id: 'WF-2026-003',
    type: 'overtime',
    requester: { id: 'EMP-012', name: 'กฤษ ธนวรรณ', position: 'DevOps Engineer', department: 'IT' },
    description: 'OT 4 ชม. — ย้ายเซิร์ฟเวอร์ production ฉุกเฉิน',
    submittedAt: '2026-04-27T16:00:00',
    urgency: 'urgent',
    waitingDays: 5,
    details: overtime({ hours: 4, date: '2026-04-26' }),
    approvalTimeline: chain('Manager A', 'HRBP'),
  },
  {
    id: 'WF-2026-004',
    type: 'claim',
    requester: { id: 'EMP-009', name: 'สมชาย ใจดี', position: 'HR Specialist', department: 'HR' },
    description: 'เบิกค่ารักษาพยาบาล OPD — 2,500 บาท',
    submittedAt: '2026-04-25T14:20:00',
    urgency: 'normal',
    waitingDays: 7,
    attachments: ['opd-receipt.pdf', 'doctor-note.pdf'],
    assignedApprover: { id: 'SPD001', name: 'ดารณี ล. (SPD)', assignedAt: '2026-04-25T15:00:00' },
    details: claim({ amount: 2500, category: 'medical', merchant: 'Samitivej Hospital' }),
    approvalTimeline: chain('HRBP', 'SPD'),
  },
  {
    id: 'WF-2026-005',
    type: 'claim',
    requester: { id: 'EMP-015', name: 'มาลี ศรีพรรณ', position: 'Accountant', department: 'Finance' },
    description: 'เบิกค่าทันตกรรม — ถอนฟัน 1,800 บาท',
    submittedAt: '2026-04-24T10:00:00',
    urgency: 'normal',
    waitingDays: 8,
    attachments: ['dental-receipt.pdf'],
    details: claim({ amount: 1800, category: 'dental', merchant: 'Dental Clinic Silom' }),
    approvalTimeline: chain('HRBP', 'SPD', 'HR Admin'),
  },
  {
    id: 'WF-2026-006',
    type: 'transfer',
    requester: { id: 'EMP-021', name: 'วิชัย ประสงค์ดี', position: 'Project Manager', department: 'Operations' },
    description: 'ขอย้ายแผนก Operations → Strategy มีผล 1 มิ.ย.',
    submittedAt: '2026-04-22T09:00:00',
    urgency: 'normal',
    waitingDays: 10,
    details: transfer(),
    approvalTimeline: chain('Manager C', 'HRBP'),
  },
  {
    id: 'WF-2026-007',
    type: 'overtime',
    requester: { id: 'EMP-003', name: 'ณัฐพงษ์ แก้วใส', position: 'Software Engineer', department: 'IT' },
    description: 'OT 2 ชม. — แก้บั๊ก production หลังเลิกงาน',
    submittedAt: '2026-04-30T21:30:00',
    urgency: 'normal',
    waitingDays: 2,
    details: overtime({ hours: 2, rate: 1.5, reason: 'แก้บั๊ก production' }),
    approvalTimeline: chain('Manager A'),
  },
  {
    id: 'WF-2026-008',
    type: 'leave',
    requester: { id: 'EMP-033', name: 'ศิริพร วงศ์ทอง', position: 'Marketing Executive', department: 'Marketing' },
    description: 'ลากิจ 0.5 วัน — ธุระส่วนตัวช่วงบ่าย',
    submittedAt: '2026-04-30T08:30:00',
    urgency: 'low',
    waitingDays: 2,
    details: leave({ leaveType: 'personal', startDate: '2026-05-02', endDate: '2026-05-02', totalDays: 0.5, balance: 5 }),
    approvalTimeline: chain('Manager D'),
  },
  {
    id: 'WF-2026-009',
    type: 'claim',
    requester: { id: 'EMP-041', name: 'ธนกร รักษาไทย', position: 'Sales Manager', department: 'Sales' },
    description: 'เบิกค่าเดินทาง — เยี่ยมลูกค้า 3,200 บาท',
    submittedAt: '2026-04-26T14:00:00',
    urgency: 'normal',
    waitingDays: 6,
    attachments: ['travel-receipt-grab.jpg', 'customer-visit-note.pdf'],
    details: claim({ amount: 3200, category: 'travel', merchant: 'BTS / Grab / Taxi' }),
    approvalTimeline: chain('Manager E', 'HRBP'),
  },
  {
    id: 'WF-2026-010',
    type: 'claim',
    requester: { id: 'EMP-056', name: 'นิดา พรสวรรค์', position: 'Data Analyst', department: 'Analytics' },
    description: 'เบิกค่าตรวจสุขภาพประจำปี 2,800 บาท',
    submittedAt: '2026-04-20T11:00:00',
    urgency: 'low',
    waitingDays: 12,
    attachments: ['annual-checkup-receipt.pdf'],
    details: claim({ amount: 2800, category: 'health_checkup', merchant: 'Vejthani Hospital' }),
    approvalTimeline: chain('HRBP', 'SPD', 'HR Admin'),
  },
  {
    id: 'WF-2026-011',
    type: 'transfer',
    requester: { id: 'EMP-062', name: 'อภิชาติ สิงห์โต', position: 'Business Analyst', department: 'IT' },
    description: 'โอนย้ายตำแหน่ง IT → Digital Transformation มีผล ก.ค.',
    submittedAt: '2026-04-18T09:15:00',
    urgency: 'normal',
    waitingDays: 14,
    details: transfer({ fromDepartment: 'IT', toDepartment: 'Digital Transformation', fromPosition: 'Business Analyst', toPosition: 'Digital Product Owner', effectiveDate: '2026-07-01' }),
    approvalTimeline: chain('Manager A', 'HRBP', 'HR Admin'),
  },
  {
    id: 'WF-2026-012',
    type: 'leave',
    requester: { id: 'EMP-074', name: 'ปรียา เทพสุวรรณ', position: 'Legal Counsel', department: 'Legal' },
    description: 'ลาคลอด 90 วัน',
    submittedAt: '2026-04-15T10:00:00',
    urgency: 'urgent',
    waitingDays: 17,
    details: leave({ leaveType: 'maternity', startDate: '2026-05-01', endDate: '2026-07-29', totalDays: 90, balance: 0, reason: 'ลาคลอด' }),
    approvalTimeline: chain('Manager F', 'HRBP', 'HR Admin'),
  },
  {
    id: 'WF-2026-013',
    type: 'overtime',
    requester: { id: 'EMP-082', name: 'ชาญชัย บุญเรือง', position: 'Network Engineer', department: 'IT' },
    description: 'OT 8 ชม. — maintenance weekend',
    submittedAt: '2026-04-29T17:00:00',
    urgency: 'normal',
    waitingDays: 3,
    details: overtime({ hours: 8, rate: 2, date: '2026-05-03', reason: 'Planned maintenance window' }),
    approvalTimeline: chain('Manager A'),
  },
  {
    id: 'WF-2026-014',
    type: 'claim',
    requester: { id: 'EMP-091', name: 'รัตนา ฤทธิ์เดช', position: 'Finance Director', department: 'Finance' },
    description: 'เบิกค่าสัมมนา — หลักสูตรผู้บริหาร 15,000 บาท',
    submittedAt: '2026-04-10T09:30:00',
    urgency: 'low',
    waitingDays: 22,
    attachments: ['seminar-invoice.pdf', 'pre-approval.pdf'],
    details: claim({ amount: 15000, category: 'training', merchant: 'SET Institute', policyChecks: [{ rule: 'Pre-approved by HR', passed: true }, { rule: 'Budget available', passed: true }] }),
    approvalTimeline: chain('HRBP', 'HR Admin'),
  },
  {
    id: 'WF-2026-015',
    type: 'leave',
    requester: { id: 'EMP-007', name: 'พลอย สุขสวัสดิ์', position: 'UX Designer', department: 'Product' },
    description: 'ลาพักร้อน 5 วัน — ท่องเที่ยวต่างประเทศ',
    submittedAt: '2026-04-28T10:00:00',
    urgency: 'low',
    waitingDays: 4,
    details: leave({ startDate: '2026-05-20', endDate: '2026-05-26', totalDays: 5, balance: 8, reason: 'ท่องเที่ยวญี่ปุ่น' }),
    approvalTimeline: chain('Manager B'),
  },
  {
    id: 'WF-2026-016',
    type: 'change_request',
    requester: { id: 'EMP-033', name: 'ศิริพร วงศ์ทอง', position: 'Marketing Executive', department: 'Marketing' },
    description: 'แก้ไขข้อมูลบัญชีธนาคาร — masked diff, pending-only withdrawal',
    submittedAt: '2026-04-27T13:00:00',
    urgency: 'normal',
    waitingDays: 5,
    details: {
      changeType: 'Bank account',
      reason: 'เปลี่ยนธนาคารหลัก',
      effectiveDate: '2026-05-15',
      approvalState: 'รออนุมัติ — employee may withdraw before decision',
      fieldDiffs: [
        { field: 'bankName', label: 'ธนาคาร', before: 'KBank', after: 'SCB', sensitive: false },
        { field: 'bank_account', label: 'เลขที่บัญชี', before: 'KBank ***1234', after: 'SCB ***5678', sensitive: true },
        { field: 'document', label: 'สำเนาสมุดบัญชี', before: 'เอกสารเดิม (masked)', after: 'mock preview only', sensitive: true },
      ],
    },
    approvalTimeline: chain('SPD'),
  },
  {
    id: 'WF-2026-017',
    type: 'claim',
    requester: { id: 'EMP-056', name: 'นิดา พรสวรรค์', position: 'Data Analyst', department: 'Analytics' },
    description: 'เบิกค่าน้ำมันรถ — เยี่ยมสาขา 1,200 บาท',
    submittedAt: '2026-04-30T15:00:00',
    urgency: 'low',
    waitingDays: 2,
    attachments: ['fuel-receipt.jpg'],
    details: claim({ amount: 1200, category: 'fuel', merchant: 'PTT Station' }),
    approvalTimeline: chain('HRBP', 'SPD'),
  },
  {
    id: 'WF-2026-018',
    type: 'overtime',
    requester: { id: 'EMP-041', name: 'ธนกร รักษาไทย', position: 'Sales Manager', department: 'Sales' },
    description: 'OT 3 ชม. — ปิดดีลลูกค้าช่วงเย็น',
    submittedAt: '2026-04-29T20:00:00',
    urgency: 'urgent',
    waitingDays: 3,
    details: overtime({ hours: 3, rate: 1.5, date: '2026-04-29', reason: 'ปิดดีลลูกค้ารายใหญ่' }),
    approvalTimeline: chain('Manager E'),
  },
  {
    id: 'WF-2026-019',
    type: 'transfer',
    requester: { id: 'EMP-015', name: 'มาลี ศรีพรรณ', position: 'Accountant', department: 'Finance' },
    description: 'ย้ายสาขา BKK → เชียงใหม่ มีผล ส.ค.',
    submittedAt: '2026-04-17T09:00:00',
    urgency: 'normal',
    waitingDays: 15,
    details: transfer({ fromDepartment: 'Finance BKK', toDepartment: 'Finance Chiang Mai', fromPosition: 'Accountant', toPosition: 'Accountant', reason: 'ย้ายภูมิลำเนา', effectiveDate: '2026-08-01' }),
    approvalTimeline: chain('Manager G', 'HRBP', 'HR Admin'),
  },
  {
    id: 'WF-2026-020',
    type: 'leave',
    requester: { id: 'EMP-091', name: 'รัตนา ฤทธิ์เดช', position: 'Finance Director', department: 'Finance' },
    description: 'ลากิจ 2 วัน — ร่วมสัมมนา AEC',
    submittedAt: '2026-04-30T08:00:00',
    urgency: 'urgent',
    waitingDays: 2,
    details: leave({ leaveType: 'personal', startDate: '2026-05-08', endDate: '2026-05-09', totalDays: 2, balance: 7, reason: 'AEC Leadership Summit' }),
    approvalTimeline: chain('HRBP'),
  },
];
