// ec-core.ts — EC-Core field catalog
//
// Every FieldDef below is grounded in one of two primary sources:
//   1. BRD-EC-summary.md row number (field `brdRow`)
//      at projects/hr-platform-replacement/BRD-EC-summary.md
//   2. SAP SuccessFactors entity schema (fields `sfEntity` + `sfField`)
//      at projects/hr-platform-replacement/docs/entity-schemas/<domain>/<ENTITY>.md
//
// Section index (for getFieldsBySection):
//   identity, name, biographical, nationalId, address, email, phone,
//   emergencyContact, familyDependent, workPermit, employmentInfo,
//   employmentDates, job, jobRelationships, compensation, payment,
//   bankAccount, termination, probation, rehire, transfer
//
// Flow index (for getFieldsByFlow):
//   hire, rehire, transfer, terminate, contractRenewal, probation, empData
//
// Scope: EC-Core Batch 1 — covers flow-09 Hire Lifecycle (BRD #109-117),
// flow-06 Personal Info (BRD #12-34), flow-08 Employment Info (BRD #85-108),
// and flow-10 Compensation (BRD #118-120). EC-FO and Benefit deferred.

import { FieldDef } from './types';

// Convenience constant — five common lifecycle flows a field participates in.
// Spelled out inline below so the "shape" of each FieldDef stays obvious
// at a glance; this is just a named alias for readability.
const LIFECYCLE_ALL: FieldDef['flowsUsedIn'] = [
  'hire', 'rehire', 'transfer', 'terminate', 'contractRenewal', 'probation', 'empData',
];

export const EC_CORE_FIELDS: FieldDef[] = [
  // ───────────────────────────────────────────────────────────────────────
  // SECTION: identity — who is being hired / rehired / transferred / etc.
  // Source: BRD #109 Hiring Flow + EC_EMP_EMPLOYMENT (root entity)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'hireDate',
    brdRow: 109,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'EFFECTIVE_START_DATE',
    labelTh: 'วันที่เข้างาน',
    labelEn: 'Hire Date',
    type: 'date',
    required: true,
    section: 'identity',
    flowsUsedIn: ['hire', 'rehire'],
  },
  {
    id: 'originalStartDate',
    brdRow: 102,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'ORIGINAL_START_DATE',
    labelTh: 'วันที่เริ่มงานเดิม (ก่อน Rehire)',
    labelEn: 'Original Start Date',
    type: 'date',
    required: false,
    section: 'identity',
    flowsUsedIn: ['rehire', 'empData'],
  },
  {
    id: 'seniorityDate',
    brdRow: 110,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'SENIORITY_DATE',
    labelTh: 'วันเริ่มอายุงานต่อเนื่อง',
    labelEn: 'Seniority Start Date',
    type: 'date',
    required: false,
    section: 'identity',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'companyCode',
    brdRow: 109,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'COMPANY_ID',
    labelTh: 'บริษัท',
    labelEn: 'Company',
    type: 'picklist',
    required: true,
    picklistId: 'FOCompany',
    section: 'identity',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'eventReason',
    brdRow: 109,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EVENT_REASON_ID',
    labelTh: 'เหตุผลของเหตุการณ์',
    labelEn: 'Event Reason',
    type: 'picklist',
    required: true,
    picklistId: 'FOEventReason',
    section: 'identity',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'event',
    brdRow: 109,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EVENT',
    labelTh: 'ประเภทเหตุการณ์',
    labelEn: 'Event',
    type: 'picklist',
    required: true,
    picklistId: 'EVENT',
    section: 'identity',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'userId',
    brdRow: null,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'USER_ID',
    labelTh: 'รหัส User',
    labelEn: 'User ID',
    type: 'string',
    required: true,
    maxLength: 15,
    readOnly: { condition: 'isEdit' },
    section: 'identity',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'personId',
    brdRow: null,
    sfEntity: 'EC_PER_PERSON',
    sfField: 'PERSON_ID',
    labelTh: 'รหัสพนักงาน',
    labelEn: 'Employee ID',
    type: 'string',
    required: true,
    maxLength: 15,
    readOnly: { condition: 'isEdit' },
    section: 'identity',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'cgPreviousEmployeeId',
    brdRow: 102,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'CG_PREVIOUS_EMPLOYEE_ID',
    labelTh: 'รหัสพนักงานเดิม (Central Group)',
    labelEn: 'CG Previous Employee ID',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'identity',
    flowsUsedIn: ['rehire', 'transfer', 'empData'],
  },
  {
    id: 'dvtPreviousId',
    brdRow: 102,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'DVT_PREVIOUS_ID',
    labelTh: 'รหัสพนักงาน DVT เดิม',
    labelEn: 'DVT Previous ID',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'identity',
    flowsUsedIn: ['rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: name — EC_PER_PERSONAL (BRD #13 Personal Info)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'salutationTh',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'SALUTATION_LOCAL',
    labelTh: 'คำนำหน้า (ไทย)',
    labelEn: 'Salutation (TH)',
    type: 'picklist',
    required: true,
    picklistId: 'SALUTATION',
    maxLength: 256,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'firstNameTh',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'FIRSTNAME_LOCAL',
    labelTh: 'ชื่อ (ไทย)',
    labelEn: 'First Name (TH)',
    type: 'string',
    required: true,
    maxLength: 40,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'middleNameTh',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'MIDDLE_NAME_LOCAL',
    labelTh: 'ชื่อกลาง (ไทย)',
    labelEn: 'Middle Name (TH)',
    type: 'string',
    required: false,
    maxLength: 40,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'lastNameTh',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'LASTNAME_LOCAL',
    labelTh: 'นามสกุล (ไทย)',
    labelEn: 'Last Name (TH)',
    type: 'string',
    required: true,
    maxLength: 40,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'salutationEn',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'SALUTATION',
    labelTh: 'คำนำหน้า (อังกฤษ)',
    labelEn: 'Salutation (EN)',
    type: 'picklist',
    required: false,
    picklistId: 'SALUTATION',
    maxLength: 128,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'firstNameEn',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'FIRST_NAME',
    labelTh: 'ชื่อ (อังกฤษ)',
    labelEn: 'First Name (EN)',
    type: 'string',
    required: true,
    maxLength: 40,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'middleNameEn',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'MIDDLE_NAME',
    labelTh: 'ชื่อกลาง (อังกฤษ)',
    labelEn: 'Middle Name (EN)',
    type: 'string',
    required: false,
    maxLength: 40,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'lastNameEn',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'LAST_NAME',
    labelTh: 'นามสกุล (อังกฤษ)',
    labelEn: 'Last Name (EN)',
    type: 'string',
    required: true,
    maxLength: 40,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'namePrefixOther',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'NAME_PREFIX',
    labelTh: 'คำนำหน้าอื่น ๆ',
    labelEn: 'Other Title (TH)',
    type: 'picklist',
    required: false,
    picklistId: 'SALUTATION_TH_OTHER',
    maxLength: 128,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nickname',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'PREFERRED_NAME',
    labelTh: 'ชื่อเล่น',
    labelEn: 'Nickname',
    type: 'string',
    required: false,
    maxLength: 128,
    section: 'name',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: biographical — BRD #12 Biographical Info + EC_PER_PERSON +
  // EC_PER_PERSONAL + EC_PER_GLOBAL_INFO_THA
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'dateOfBirth',
    brdRow: 12,
    sfEntity: 'EC_PER_PERSON',
    sfField: 'DATE_OF_BIRTH',
    labelTh: 'วันเกิด',
    labelEn: 'Date of Birth',
    type: 'date',
    required: true,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'countryOfBirth',
    brdRow: 12,
    sfEntity: 'EC_PER_PERSON',
    sfField: 'COUNTRY_OF_BIRTH',
    labelTh: 'ประเทศที่เกิด',
    labelEn: 'Country of Birth',
    type: 'picklist',
    required: false,
    picklistId: 'FOTerritory',
    maxLength: 100,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'regionOfBirth',
    brdRow: 12,
    sfEntity: 'EC_PER_PERSON',
    sfField: 'REGION_OF_BIRTH',
    labelTh: 'ภูมิภาคที่เกิด',
    labelEn: 'Region of Birth',
    type: 'string',
    required: false,
    maxLength: 100,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'gender',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'GENDER',
    labelTh: 'เพศ',
    labelEn: 'Gender',
    type: 'picklist',
    required: true,
    picklistId: 'GENDER',
    maxLength: 2,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nationality',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'NATIONALITY',
    labelTh: 'สัญชาติ',
    labelEn: 'Nationality',
    type: 'picklist',
    required: true,
    picklistId: 'Nationality',
    maxLength: 128,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'foreigner',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'FOREIGNER',
    labelTh: 'เป็นชาวต่างชาติหรือไม่',
    labelEn: 'Foreigner',
    type: 'picklist',
    required: true,
    picklistId: 'YES_NO',
    maxLength: 256,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'bloodType',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'BLOOD_TYPE',
    labelTh: 'กรุ๊ปเลือด',
    labelEn: 'Blood Type',
    type: 'picklist',
    required: false,
    picklistId: 'BLOODGROUP',
    maxLength: 256,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'maritalStatus',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'MARITAL_STATUS',
    labelTh: 'สถานภาพสมรส',
    labelEn: 'Marital Status',
    type: 'picklist',
    required: true,
    picklistId: 'MARITAL_STATUS',
    maxLength: 50,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'maritalStatusSince',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'MILITARY_STATUS_SINCE',
    labelTh: 'วันที่สถานภาพสมรสมีผล',
    labelEn: 'Marital Status Since',
    type: 'date',
    required: false,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'militaryStatus',
    brdRow: 13,
    sfEntity: 'EC_PER_PERSONAL',
    sfField: 'MILITARY_STATUS',
    labelTh: 'สถานะทางทหาร',
    labelEn: 'Military Status',
    type: 'picklist',
    required: false,
    picklistId: 'MILLITARY_STATUS',
    maxLength: 256,
    visibleWhen: "gender === 'M'",
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'religion',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'RELIGION',
    labelTh: 'ศาสนา',
    labelEn: 'Religion',
    type: 'picklist',
    required: true,
    picklistId: 'RELIGION_THA',
    maxLength: 256,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'disabilityStatus',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'DISABILITY_STATUS',
    labelTh: 'สถานะความพิการ',
    labelEn: 'Disability Status',
    type: 'picklist',
    required: false,
    picklistId: 'YES_NO',
    maxLength: 256,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'typeOfDisability',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'TYPEOF_DISABILITY',
    labelTh: 'ประเภทความพิการ',
    labelEn: 'Type of Disability',
    type: 'picklist',
    required: false,
    picklistId: 'TYPE_OF_CHALLENGE',
    maxLength: 256,
    visibleWhen: "disabilityStatus === 'YES'",
    mandatoryWhen: "disabilityStatus === 'YES'",
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'disabilityCertificateId',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'CERTIFICATEID',
    labelTh: 'เลขที่บัตรประจำตัวคนพิการ',
    labelEn: 'Disability Certificate ID',
    type: 'string',
    required: false,
    maxLength: 256,
    visibleWhen: "disabilityStatus === 'YES'",
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'disabilityCertificateStartDate',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'DISABILITY_CERTIFICATE_START_DATE',
    labelTh: 'วันที่เริ่มบัตรประจำตัวคนพิการ',
    labelEn: 'Disability Certificate Start Date',
    type: 'date',
    required: false,
    visibleWhen: "disabilityStatus === 'YES'",
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'disabilityCertificateEndDate',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'DISABILITY_CERTIFICATE_END_DATE',
    labelTh: 'วันที่สิ้นสุดบัตรประจำตัวคนพิการ',
    labelEn: 'Disability Certificate End Date',
    type: 'date',
    required: false,
    visibleWhen: "disabilityStatus === 'YES'",
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'numberOfChildren',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'NUMBEROF_CHILDREN',
    labelTh: 'จำนวนบุตร',
    labelEn: 'Number of Children',
    type: 'number',
    required: false,
    section: 'biographical',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'deceased',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'DECEASED',
    labelTh: 'เสียชีวิตแล้ว',
    labelEn: 'Deceased',
    type: 'picklist',
    required: false,
    picklistId: 'YES_NO',
    maxLength: 2,
    section: 'biographical',
    flowsUsedIn: ['empData', 'terminate'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: nationalId — BRD #14 + EC_PER_NATIONAL_ID
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'nationalIdCardType',
    brdRow: 14,
    sfEntity: 'EC_PER_NATIONAL_ID',
    sfField: 'CARD_TYPE_ID',
    labelTh: 'ประเภทบัตรประจำตัว',
    labelEn: 'National ID Card Type',
    type: 'picklist',
    required: true,
    picklistId: 'FONationalIdCardType',
    section: 'nationalId',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nationalId',
    brdRow: 14,
    sfEntity: 'EC_PER_NATIONAL_ID',
    sfField: 'NATIONAL_ID',
    labelTh: 'เลขประจำตัวประชาชน',
    labelEn: 'National ID',
    type: 'string',
    required: true,
    maxLength: 256,
    minLength: 13,
    regex: '^[0-9]{13}$',
    section: 'nationalId',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nationalIdCountry',
    brdRow: 14,
    sfEntity: 'EC_PER_NATIONAL_ID',
    sfField: 'COUNTRY',
    labelTh: 'ประเทศของบัตร',
    labelEn: 'Country',
    type: 'picklist',
    required: true,
    picklistId: 'FOTerritory',
    maxLength: 100,
    defaultValue: 'THA',
    section: 'nationalId',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nationalIdIssueDate',
    brdRow: 14,
    sfEntity: 'EC_PER_NATIONAL_ID',
    sfField: 'ISSUE_DATE',
    labelTh: 'วันที่ออกบัตร',
    labelEn: 'Issue Date',
    type: 'date',
    required: false,
    section: 'nationalId',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nationalIdExpiryDate',
    brdRow: 14,
    sfEntity: 'EC_PER_NATIONAL_ID',
    sfField: 'EXPIRY_DATE',
    labelTh: 'วันที่บัตรหมดอายุ',
    labelEn: 'Expiry Date',
    type: 'date',
    required: false,
    section: 'nationalId',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nationalIdIsPrimary',
    brdRow: 14,
    sfEntity: 'EC_PER_NATIONAL_ID',
    sfField: 'IS_PRIMARY',
    labelTh: 'เป็นบัตรหลัก',
    labelEn: 'Is Primary',
    type: 'boolean',
    required: false,
    defaultValue: true,
    section: 'nationalId',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'nationalIdAttachment',
    brdRow: 14,
    sfEntity: 'EC_PER_NATIONAL_ID',
    sfField: 'ATTACHMENT_ID',
    labelTh: 'ไฟล์แนบสำเนาบัตร',
    labelEn: 'Attachment',
    type: 'string',
    required: false,
    section: 'nationalId',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: address — BRD #17 Address + EC_PER_ADDRESS
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'addressType',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'ADDRESS_TYPE',
    labelTh: 'ประเภทที่อยู่',
    labelEn: 'Address Type',
    type: 'picklist',
    required: true,
    picklistId: 'ADDRESS_TYPE',
    maxLength: 30,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressHouseStreetNumber',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'HOUSE_STREET_NUMBER',
    labelTh: 'บ้านเลขที่ / ถนน',
    labelEn: 'House / Street Number',
    type: 'string',
    required: true,
    maxLength: 256,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressVillage',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'VILLAGE',
    labelTh: 'หมู่บ้าน / หมู่ที่',
    labelEn: 'Village / Moo',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressAlley',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'ALLEY',
    labelTh: 'ตรอก / ซอย',
    labelEn: 'Lane / Soi',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressRoad',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'ROAD',
    labelTh: 'ถนน',
    labelEn: 'Road',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  // BRD #17 explicitly mandates the waterfall Province → District → Sub-district → Postcode.
  {
    id: 'addressProvince',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'PROVINCE',
    labelTh: 'จังหวัด',
    labelEn: 'Province',
    type: 'picklist',
    required: true,
    picklistId: 'ADDRESS_PROVINCE',
    maxLength: 256,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressDistrict',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'DISTRICT',
    labelTh: 'เขต / อำเภอ',
    labelEn: 'District',
    type: 'picklist',
    required: true,
    picklistId: 'ADDRESS_DISTRICT',
    maxLength: 256,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressSubDistrict',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'SUB_DISTRICT',
    labelTh: 'แขวง / ตำบล',
    labelEn: 'Sub-District',
    type: 'picklist',
    required: true,
    picklistId: 'ADDRESS_SUB_DISTRICT',
    maxLength: 256,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressPostalCode',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'POSTAL_CODE',
    labelTh: 'รหัสไปรษณีย์',
    labelEn: 'Postal Code',
    type: 'string',
    required: true,
    maxLength: 256,
    regex: '^[0-9]{5}$',
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressCountry',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'COUNTRY_ID',
    labelTh: 'ประเทศ',
    labelEn: 'Country',
    type: 'picklist',
    required: true,
    picklistId: 'FOTerritory',
    maxLength: 256,
    defaultValue: 'THA',
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'addressEffectiveStartDate',
    brdRow: 17,
    sfEntity: 'EC_PER_ADDRESS',
    sfField: 'EFFECTIVE_START_DATE',
    labelTh: 'วันที่ที่อยู่มีผล',
    labelEn: 'Address Effective Date',
    type: 'date',
    required: true,
    section: 'address',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: email — BRD #15 Email Info + EC_PER_EMAIL
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'emailType',
    brdRow: 15,
    sfEntity: 'EC_PER_EMAIL',
    sfField: 'EMAIL_TYPE',
    labelTh: 'ประเภทอีเมล',
    labelEn: 'Email Type',
    type: 'picklist',
    required: true,
    picklistId: 'EMAIL_TYPE',
    maxLength: 38,
    section: 'email',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emailAddress',
    brdRow: 15,
    sfEntity: 'EC_PER_EMAIL',
    sfField: 'EMAIL_ADDRESS',
    labelTh: 'อีเมล',
    labelEn: 'Email Address',
    type: 'string',
    required: true,
    maxLength: 100,
    regex: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
    section: 'email',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emailIsPrimary',
    brdRow: 15,
    sfEntity: 'EC_PER_EMAIL',
    sfField: 'IS_PRIMARY',
    labelTh: 'เป็นอีเมลหลัก',
    labelEn: 'Is Primary',
    type: 'boolean',
    required: false,
    defaultValue: true,
    section: 'email',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'personalEmailResign',
    brdRow: 111,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'PERSONAL_EMAIL_RESIGN',
    labelTh: 'อีเมลส่วนตัวสำหรับรับเอกสาร 50 ทวิ',
    labelEn: 'Personal Email (For 50-Tawi / Payslip)',
    type: 'string',
    required: true,
    maxLength: 256,
    regex: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
    section: 'email',
    flowsUsedIn: ['terminate'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: phone — BRD #16 Phone Info + EC_PER_PHONE
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'phoneType',
    brdRow: 16,
    sfEntity: 'EC_PER_PHONE',
    sfField: 'PHONE_TYPE',
    labelTh: 'ประเภทเบอร์โทรศัพท์',
    labelEn: 'Phone Type',
    type: 'picklist',
    required: true,
    picklistId: 'PHONE_TYPE',
    maxLength: 100,
    section: 'phone',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'phoneNumber',
    brdRow: 16,
    sfEntity: 'EC_PER_PHONE',
    sfField: 'PHONE_NUMBER',
    labelTh: 'เบอร์โทรศัพท์',
    labelEn: 'Phone Number',
    type: 'string',
    required: true,
    maxLength: 100,
    regex: '^(\\+66|0)[0-9]{8,9}$',
    section: 'phone',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'phoneCountryCode',
    brdRow: 16,
    sfEntity: 'EC_PER_PHONE',
    sfField: 'COUNTRY_CODE',
    labelTh: 'รหัสประเทศ',
    labelEn: 'Country Code',
    type: 'string',
    required: false,
    maxLength: 32,
    defaultValue: '+66',
    section: 'phone',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'phoneExtension',
    brdRow: 16,
    sfEntity: 'EC_PER_PHONE',
    sfField: 'EXTENSION',
    labelTh: 'เบอร์ต่อภายใน',
    labelEn: 'Extension',
    type: 'string',
    required: false,
    maxLength: 32,
    section: 'phone',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'phoneIsPrimary',
    brdRow: 16,
    sfEntity: 'EC_PER_PHONE',
    sfField: 'IS_PRIMARY',
    labelTh: 'เป็นเบอร์หลัก',
    labelEn: 'Is Primary',
    type: 'boolean',
    required: false,
    defaultValue: true,
    section: 'phone',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: emergencyContact — BRD #19 + EC_PER_EMERGENCY_CONTACTS
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'emergencyContactName',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'CONTACT_NAME',
    labelTh: 'ชื่อผู้ติดต่อฉุกเฉิน',
    labelEn: 'Emergency Contact Name',
    type: 'string',
    required: true,
    maxLength: 256,
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emergencyContactRelationship',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'RELATIONSHIP',
    labelTh: 'ความสัมพันธ์',
    labelEn: 'Relationship',
    type: 'picklist',
    required: true,
    picklistId: 'PERSON_RELATIONSHIP',
    maxLength: 50,
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emergencyContactPhone',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'PHONE',
    labelTh: 'เบอร์ติดต่อฉุกเฉิน',
    labelEn: 'Emergency Contact Phone',
    type: 'string',
    required: true,
    maxLength: 256,
    regex: '^(\\+66|0)[0-9]{8,9}$',
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emergencyContactIsAddSameAsEmployee',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'IS_ADD_SAME_AS_EMPLOYEE',
    labelTh: 'ใช้ที่อยู่เดียวกับพนักงาน',
    labelEn: 'Copy Address from Employee',
    type: 'boolean',
    required: false,
    defaultValue: true,
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emergencyContactHouseStreetNumber',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'HOUSE_STREET_NUMBER',
    labelTh: 'บ้านเลขที่ผู้ติดต่อฉุกเฉิน',
    labelEn: 'Emergency House / Street Number',
    type: 'string',
    required: false,
    maxLength: 256,
    visibleWhen: 'emergencyContactIsAddSameAsEmployee === false',
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emergencyContactProvince',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'PROVINCE',
    labelTh: 'จังหวัดผู้ติดต่อฉุกเฉิน',
    labelEn: 'Emergency Province',
    type: 'picklist',
    required: false,
    picklistId: 'ADDRESS_PROVINCE',
    maxLength: 256,
    visibleWhen: 'emergencyContactIsAddSameAsEmployee === false',
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emergencyContactPostalCode',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'POSTAL_CODE',
    labelTh: 'รหัสไปรษณีย์ผู้ติดต่อฉุกเฉิน',
    labelEn: 'Emergency Postal Code',
    type: 'string',
    required: false,
    maxLength: 256,
    visibleWhen: 'emergencyContactIsAddSameAsEmployee === false',
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'emergencyContactPrimaryFlag',
    brdRow: 19,
    sfEntity: 'EC_PER_EMERGENCY_CONTACTS',
    sfField: 'PRIMARY_FLAG',
    labelTh: 'เป็นผู้ติดต่อฉุกเฉินหลัก',
    labelEn: 'Primary Emergency Contact',
    type: 'boolean',
    required: false,
    defaultValue: true,
    section: 'emergencyContact',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: familyDependent — BRD #20 Dependents + EC_PER_PERSON_RELATIONSHIP
  //                          + EC_PER_GLOBAL_INFO_THA (spouse IDs / tax)
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'dependentRelationshipType',
    brdRow: 20,
    sfEntity: 'EC_PER_PERSON_RELATIONSHIP',
    sfField: 'RELATIONSHIP_TYPE',
    labelTh: 'ประเภทความสัมพันธ์',
    labelEn: 'Relationship Type',
    type: 'picklist',
    required: true,
    picklistId: 'PERSON_RELATIONSHIP_TYPE',
    maxLength: 30,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'dependentFirstNameEn',
    brdRow: 20,
    sfEntity: 'EC_PER_PERSON_RELATIONSHIP',
    sfField: 'FIRST_NAME',
    labelTh: 'ชื่อผู้พึ่งพิง (อังกฤษ)',
    labelEn: 'Dependent First Name (EN)',
    type: 'string',
    required: true,
    maxLength: 128,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'dependentLastNameEn',
    brdRow: 20,
    sfEntity: 'EC_PER_PERSON_RELATIONSHIP',
    sfField: 'LAST_NAME',
    labelTh: 'นามสกุลผู้พึ่งพิง (อังกฤษ)',
    labelEn: 'Dependent Last Name (EN)',
    type: 'string',
    required: true,
    maxLength: 128,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'dependentIsAddressSameAsPerson',
    brdRow: 20,
    sfEntity: 'EC_PER_PERSON_RELATIONSHIP',
    sfField: 'IS_ADDRESS_SAME_AS_PERSON',
    labelTh: 'ใช้ที่อยู่เดียวกับพนักงาน',
    labelEn: 'Copy Address from Employee',
    type: 'boolean',
    required: false,
    defaultValue: true,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'dependentIsBeneficiary',
    brdRow: 20,
    sfEntity: 'EC_PER_PERSON_RELATIONSHIP',
    sfField: 'IS_BENEFICIARY',
    labelTh: 'เป็นผู้รับผลประโยชน์',
    labelEn: 'Is Beneficiary',
    type: 'boolean',
    required: false,
    defaultValue: false,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'dependentEffectiveStartDate',
    brdRow: 20,
    sfEntity: 'EC_PER_PERSON_RELATIONSHIP',
    sfField: 'EFFECTIVE_START_DATE',
    labelTh: 'วันที่มีผล',
    labelEn: 'Effective Start Date',
    type: 'date',
    required: true,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'spouseFatherIdNumber',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'SPOUSES_FATHERID_NUMBER',
    labelTh: 'เลขบัตรบิดาของคู่สมรส',
    labelEn: "Spouse's Father ID Number",
    type: 'string',
    required: false,
    visibleWhen: "maritalStatus === 'MARRIED'",
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'spouseMotherIdNumber',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'SPOUSES_MOTHERID_NUMBER',
    labelTh: 'เลขบัตรมารดาของคู่สมรส',
    labelEn: "Spouse's Mother ID Number",
    type: 'string',
    required: false,
    visibleWhen: "maritalStatus === 'MARRIED'",
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'dependentTaxNumber',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'DEPENDENT_TAX_NUMBER',
    labelTh: 'เลขประจำตัวผู้เสียภาษีของผู้พึ่งพิง',
    labelEn: 'Dependent Tax Number',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'taxDependent',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'TAX_DEPENDENT',
    labelTh: 'เป็นผู้พึ่งพิงทางภาษี',
    labelEn: 'Tax Dependent',
    type: 'picklist',
    required: false,
    picklistId: 'YES_NO',
    maxLength: 256,
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'taxDeductionEndDate',
    brdRow: 13,
    sfEntity: 'EC_PER_GLOBAL_INFO_THA',
    sfField: 'DEDUCTION_END_DATE',
    labelTh: 'วันที่สิ้นสุดการลดหย่อนภาษี',
    labelEn: 'Tax Deduction End Date',
    type: 'date',
    required: false,
    visibleWhen: "taxDependent === 'YES'",
    section: 'familyDependent',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: workPermit — BRD #18 Work Permit + EC_EMP_WORK_PERMIT
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'workPermitCountry',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: 'COUNTRY',
    labelTh: 'ประเทศของใบอนุญาตทำงาน',
    labelEn: 'Work Permit Country',
    type: 'picklist',
    required: true,
    picklistId: 'ISO_COUNTRY',
    maxLength: 256,
    visibleWhen: "foreigner === 'YES'",
    mandatoryWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'workPermitDocumentType',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: 'DOCUMENT_TYPE',
    labelTh: 'ประเภทเอกสารอนุญาตทำงาน',
    labelEn: 'Work Permit Document Type',
    type: 'picklist',
    required: true,
    picklistId: 'WORK_PERMIT_DOC_TYPE',
    maxLength: 256,
    visibleWhen: "foreigner === 'YES'",
    mandatoryWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'workPermitDocumentNumber',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: 'DOCUMENT_NUMBER',
    labelTh: 'เลขที่เอกสารอนุญาตทำงาน',
    labelEn: 'Work Permit Document Number',
    type: 'string',
    required: true,
    maxLength: 256,
    visibleWhen: "foreigner === 'YES'",
    mandatoryWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'workPermitIssueDate',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: 'ISSUE_DATE',
    labelTh: 'วันที่ออกเอกสาร',
    labelEn: 'Work Permit Issue Date',
    type: 'date',
    required: true,
    visibleWhen: "foreigner === 'YES'",
    mandatoryWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'workPermitExpirationDate',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: 'EXPIRATION_DATE',
    labelTh: 'วันที่หมดอายุเอกสาร',
    labelEn: 'Work Permit Expiration Date',
    type: 'date',
    required: true,
    visibleWhen: "foreigner === 'YES'",
    mandatoryWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'workPermitArrivalDate',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: 'ARRIVAL_DATE_VISA',
    labelTh: 'วันที่เดินทางเข้าประเทศ (VISA)',
    labelEn: 'Arrival Date (VISA)',
    type: 'date',
    required: false,
    visibleWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'workPermit90DaysReport',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: '90DAYS_REPORT_VISA',
    labelTh: 'วันที่รายงานตัว 90 วัน',
    labelEn: '90-Day Report (VISA)',
    type: 'date',
    required: false,
    visibleWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'workPermitAttachment',
    brdRow: 18,
    sfEntity: 'EC_EMP_WORK_PERMIT',
    sfField: 'ATTACHMENT_ID',
    labelTh: 'ไฟล์แนบเอกสารอนุญาตทำงาน',
    labelEn: 'Work Permit Attachment',
    type: 'string',
    required: false,
    visibleWhen: "foreigner === 'YES'",
    section: 'workPermit',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: employmentInfo — BRD #21 Employment + EC_EMP_EMPLOYMENT dates
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'passProbationDate',
    brdRow: 117,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'PASS_PROBATION_DATE_CONFIRM_DATE',
    labelTh: 'วันที่ผ่านทดลองงาน',
    labelEn: 'Pass Probation / Confirm Date',
    type: 'date',
    required: false,
    section: 'employmentDates',
    flowsUsedIn: ['probation', 'empData'],
  },
  {
    id: 'retirementDate',
    brdRow: 21,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'RETIREMENT_DATE',
    labelTh: 'วันที่เกษียณอายุ',
    labelEn: 'Retirement Date',
    type: 'date',
    required: false,
    section: 'employmentDates',
    flowsUsedIn: ['empData', 'terminate'],
  },
  {
    id: 'providentFundServiceDate',
    brdRow: 21,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'PF_SERVICE_DATE',
    labelTh: 'วันที่เริ่มกองทุนสำรองเลี้ยงชีพ',
    labelEn: 'Provident Fund Service Date',
    type: 'date',
    required: false,
    section: 'employmentDates',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'yearOfService',
    brdRow: 86,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'YEAR_OF_SERVICE',
    labelTh: 'อายุงาน',
    labelEn: 'Year of Service',
    type: 'string',
    required: false,
    maxLength: 256,
    readOnly: {},
    section: 'employmentDates',
    flowsUsedIn: ['empData', 'terminate'],
  },
  {
    id: 'employeeAgeYmd',
    brdRow: 93,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'EMPLOYEE_AGE_YMD',
    labelTh: 'อายุพนักงาน (ปี/เดือน/วัน)',
    labelEn: 'Employee Age (Y/M/D)',
    type: 'string',
    required: false,
    maxLength: 256,
    readOnly: {},
    section: 'employmentDates',
    flowsUsedIn: ['empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: job — BRD #23 Emp Job Info + EC_EMP_JOB
  // Organizational assignment. Required across Hire / Rehire / Transfer.
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'employeeStatus',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EMPLOYEE_STATUS',
    labelTh: 'สถานะพนักงาน',
    labelEn: 'Employee Status',
    type: 'picklist',
    required: true,
    picklistId: 'EMPLOYEE_STATUS',
    maxLength: 32,
    section: 'job',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'employeeClass',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EMPLOYEE_GROUP_ID',
    labelTh: 'ประเภทพนักงาน',
    labelEn: 'Employee Class',
    type: 'picklist',
    required: true,
    picklistId: 'cust_EmployeeClass',
    section: 'job',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'employmentType',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EMPLOYEE_SUBGROUP_ID',
    labelTh: 'ประเภทการจ้างงาน',
    labelEn: 'Employment Type',
    type: 'picklist',
    required: true,
    picklistId: 'cust_EmploymentType',
    section: 'job',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'contractType',
    brdRow: 115,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'CONTRACT_TYPE',
    labelTh: 'ประเภทสัญญาจ้าง',
    labelEn: 'Contract Type',
    type: 'picklist',
    required: false,
    picklistId: 'CONTRACT_TYPE',
    maxLength: 256,
    visibleWhen: "employeeClass === 'CONTRACT'",
    mandatoryWhen: "employeeClass === 'CONTRACT'",
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'contractRenewal'],
  },
  {
    id: 'contractEndDate',
    brdRow: 115,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'CONTRACT_END_DATE',
    labelTh: 'วันที่สิ้นสุดสัญญา',
    labelEn: 'Contract End Date',
    type: 'date',
    required: false,
    visibleWhen: "employeeClass === 'CONTRACT'",
    mandatoryWhen: "employeeClass === 'CONTRACT'",
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'contractRenewal'],
  },
  {
    id: 'isFulltimeEmployee',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'IS_FULLTIME_EMPLOYEE',
    labelTh: 'พนักงานประจำ',
    labelEn: 'Is Full Time Employee',
    type: 'boolean',
    required: true,
    defaultValue: true,
    section: 'job',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'fte',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'FTE',
    labelTh: 'อัตราส่วน FTE',
    labelEn: 'FTE',
    type: 'number',
    required: true,
    defaultValue: 1,
    section: 'job',
    flowsUsedIn: LIFECYCLE_ALL,
  },
  {
    id: 'position',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'POSITION_ID',
    labelTh: 'ตำแหน่งงาน',
    labelEn: 'Position',
    type: 'picklist',
    required: true,
    picklistId: 'ECPosition',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'jobCode',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'JOB_CODE_ID',
    labelTh: 'รหัสงาน (Job Code)',
    labelEn: 'Job Code',
    type: 'picklist',
    required: true,
    picklistId: 'JobClassification',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'jobTitle',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'JOB_TITLE_ID',
    labelTh: 'ชื่อตำแหน่งงาน',
    labelEn: 'Job Title',
    type: 'string',
    required: true,
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'jobFamily',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'JOB_FAMILY_ID',
    labelTh: 'กลุ่มงาน (Job Family)',
    labelEn: 'Job Family',
    type: 'picklist',
    required: false,
    picklistId: 'JobFunction',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'jobType',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'JOB_TYPE',
    labelTh: 'ประเภทงาน',
    labelEn: 'Job Type',
    type: 'picklist',
    required: false,
    picklistId: 'JOB_TYPE',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'corporateTitle',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'CORPORATE_TITLE',
    labelTh: 'ตำแหน่งระดับองค์กร',
    labelEn: 'Corporate Title',
    type: 'picklist',
    required: false,
    picklistId: 'CORPORATE_TITLE',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'band',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'BAND',
    labelTh: 'Band',
    labelEn: 'Band',
    type: 'picklist',
    required: false,
    picklistId: 'NEW_CORPORATE_TITLE',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'payGrade',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'PAY_GRADE_ID',
    labelTh: 'เกรดเงินเดือน (PG)',
    labelEn: 'Pay Grade',
    type: 'picklist',
    required: true,
    picklistId: 'FOPayGrade',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'jobGrade',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'JOB_GRADE_ID',
    labelTh: 'เกรดตำแหน่ง (JG)',
    labelEn: 'Job Grade',
    type: 'picklist',
    required: true,
    picklistId: 'FOJobGrade',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'companyId',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'COMPANY_ID',
    labelTh: 'บริษัทที่สังกัด (Job)',
    labelEn: 'Company (Job)',
    type: 'picklist',
    required: true,
    picklistId: 'FOCompany',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'businessGroup',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'BUSINESS_GROUP_ID',
    labelTh: 'กลุ่มธุรกิจ',
    labelEn: 'Business Group',
    type: 'picklist',
    required: true,
    picklistId: 'FOBusinessGroup',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'businessUnit',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'BUSINESS_UNIT_ID',
    labelTh: 'หน่วยธุรกิจ',
    labelEn: 'Business Unit',
    type: 'picklist',
    required: true,
    picklistId: 'FOBusinessUnit',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'division',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'DIVISION_ID',
    labelTh: 'Function / Division',
    labelEn: 'Division (Function)',
    type: 'picklist',
    required: true,
    picklistId: 'FODivision',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'department',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'DEPARTMENT_ID',
    labelTh: 'หน่วยงาน (Organization)',
    labelEn: 'Department',
    type: 'picklist',
    required: true,
    picklistId: 'FODepartment',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'costCenter',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'COST_CENTER_ID',
    labelTh: 'Cost Center',
    labelEn: 'Cost Center',
    type: 'picklist',
    required: true,
    picklistId: 'FOCostCenter',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'location',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'LOCATION_ID',
    labelTh: 'สาขา / สถานที่ทำงาน',
    labelEn: 'Store / Branch Code',
    type: 'picklist',
    required: true,
    picklistId: 'FOLocation',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'workLocation',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'WORK_LOCATION_ID',
    labelTh: 'สถานที่ปฏิบัติงานจริง',
    labelEn: 'Work Location',
    type: 'picklist',
    required: false,
    picklistId: 'FOWorkLocation',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'ssoLocation',
    brdRow: 97,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'SSO_LOCATION_ID',
    labelTh: 'สาขาประกันสังคม',
    labelEn: 'SSO Location',
    type: 'picklist',
    required: false,
    picklistId: 'FOSSOLocation',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'zone',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'ZONE_ID',
    labelTh: 'Zone',
    labelEn: 'Zone',
    type: 'picklist',
    required: false,
    picklistId: 'cust_zone',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'hrDistrict',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'HR_DISTRICT_ID',
    labelTh: 'HR District',
    labelEn: 'HR District',
    type: 'picklist',
    required: false,
    picklistId: 'cust_HRDistrict',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'storeFormat',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'STORE_FORMAT_ID',
    labelTh: 'รูปแบบสาขา',
    labelEn: 'Store Format',
    type: 'picklist',
    required: false,
    picklistId: 'cust_StoreFormat',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'storeSize',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'STORE_SIZE',
    labelTh: 'ขนาดสาขา',
    labelEn: 'Store Size',
    type: 'picklist',
    required: false,
    picklistId: 'STORE_SIZE',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'brand',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'BRAND_ID',
    labelTh: 'แบรนด์',
    labelEn: 'Brand',
    type: 'picklist',
    required: false,
    picklistId: 'cust_brand',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'managerId',
    brdRow: 24,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'MANAGER_ID',
    labelTh: 'รหัสหัวหน้างาน (Solid)',
    labelEn: 'Manager ID (Solid)',
    type: 'string',
    required: true,
    maxLength: 256,
    section: 'jobRelationships',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'workingHour',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'WORKING_HOUR_ID',
    labelTh: 'ชั่วโมงการทำงานมาตรฐานต่อสัปดาห์',
    labelEn: 'Standard Weekly Hours',
    type: 'picklist',
    required: false,
    picklistId: 'TMWorkingHour',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'workSchedule',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'WORK_SCHEDULE_ID',
    labelTh: 'ตารางการทำงาน',
    labelEn: 'Work Schedule',
    type: 'picklist',
    required: false,
    picklistId: 'TMWorkSchedule',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'holidayCalendar',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'HOLIDAY_CALENDAR_ID',
    labelTh: 'ปฏิทินวันหยุด',
    labelEn: 'Holiday Calendar',
    type: 'picklist',
    required: false,
    picklistId: 'TMHolidayCalendar',
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'otFlag',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'OT_FLAG',
    labelTh: 'สิทธิ์ทำ OT',
    labelEn: 'OT Flag',
    type: 'picklist',
    required: false,
    picklistId: 'TMOTFlag',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'policyProfile',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'POLICY_PROFILE',
    labelTh: 'Policy Profile',
    labelEn: 'Policy Profile',
    type: 'picklist',
    required: false,
    picklistId: 'cust_policyProfile',
    maxLength: 20,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'leaveQuota',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'LEAVE_QUOTA',
    labelTh: 'โควต้าการลา',
    labelEn: 'Leave Quota',
    type: 'number',
    required: false,
    readOnly: {},
    section: 'job',
    flowsUsedIn: ['empData'],
  },
  {
    id: 'typeOfManagementProgram',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'TYPEOF_MANAGEMENT_PROGRAM',
    labelTh: 'ประเภท Management Program',
    labelEn: 'Type of Management Program',
    type: 'picklist',
    required: false,
    picklistId: 'MANAGEMENT_PROGRAM',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'typeOfGroupFamilyEmployee',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'TYPEOF_GROUP_FAMILY_EMPLOYEE',
    labelTh: 'ประเภทพนักงานในกลุ่ม',
    labelEn: 'Type of Group Family Employee',
    type: 'picklist',
    required: false,
    picklistId: 'TYPE_OF_GROUP_FAMILY',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'unionFee',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'UNION_FEE',
    labelTh: 'สมาชิกสหภาพ / จ่ายค่าสหภาพ',
    labelEn: 'Union Fee',
    type: 'picklist',
    required: false,
    picklistId: 'YES_NO',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'specialBenefitGroup',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'SPECIAL_BENEFIT_GROUP',
    labelTh: 'อยู่ในกลุ่มสวัสดิการพิเศษ',
    labelEn: 'Special Benefit Group',
    type: 'picklist',
    required: false,
    picklistId: 'YES_NO',
    maxLength: 256,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'effectiveStartDateJob',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EFFECTIVE_START_DATE',
    labelTh: 'วันที่รายการ Job มีผล',
    labelEn: 'Job Effective Start Date',
    type: 'date',
    required: true,
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'seqNumber',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'SEQ_NUMBER',
    labelTh: 'ลำดับประวัติ',
    labelEn: 'Sequence Number',
    type: 'number',
    required: true,
    defaultValue: 1,
    readOnly: {},
    section: 'job',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: jobRelationships — BRD #24 + EC_EMP_JOB_RELATIONSHIPS
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'jobRelationshipType',
    brdRow: 24,
    sfEntity: 'EC_EMP_JOB_RELATIONSHIPS',
    sfField: 'RELATIONSHIP_TYPE',
    labelTh: 'ประเภทความสัมพันธ์งาน',
    labelEn: 'Job Relationship Type',
    type: 'picklist',
    required: true,
    picklistId: 'JOB_RELATIONSHIP_TYPE',
    maxLength: 100,
    section: 'jobRelationships',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'jobRelationshipRelatedUserId',
    brdRow: 24,
    sfEntity: 'EC_EMP_JOB_RELATIONSHIPS',
    sfField: 'RELATED_USER_ID',
    labelTh: 'รหัส User ที่เกี่ยวข้อง',
    labelEn: 'Related User ID',
    type: 'string',
    required: true,
    maxLength: 15,
    section: 'jobRelationships',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'jobRelationshipEffectiveStartDate',
    brdRow: 24,
    sfEntity: 'EC_EMP_JOB_RELATIONSHIPS',
    sfField: 'EFFECTIVE_START_DATE',
    labelTh: 'วันที่ความสัมพันธ์มีผล',
    labelEn: 'Relationship Start Date',
    type: 'date',
    required: true,
    section: 'jobRelationships',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: probation — BRD #117 Pass Probation + EC_EMP_JOB probation fields
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'passProbation',
    brdRow: 117,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'PASS_PROBATION',
    labelTh: 'ผ่านทดลองงาน',
    labelEn: 'Pass Probation',
    type: 'picklist',
    required: true,
    picklistId: 'YES_NO',
    maxLength: 256,
    section: 'probation',
    flowsUsedIn: ['probation'],
  },
  {
    id: 'probationPeriodEndDate',
    brdRow: 117,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'PROBATION_PERIOD_END_DATE',
    labelTh: 'วันที่สิ้นสุดช่วงทดลองงาน',
    labelEn: 'Probation Period End Date',
    type: 'date',
    required: true,
    section: 'probation',
    flowsUsedIn: ['hire', 'rehire', 'probation'],
  },
  {
    id: 'extendedProbationDate',
    brdRow: 117,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EXTENED_PROBATION_DATE',
    labelTh: 'วันที่ขยายระยะทดลองงาน',
    labelEn: 'Extended Probation Date',
    type: 'date',
    required: false,
    visibleWhen: "passProbation === 'EXTEND'",
    mandatoryWhen: "passProbation === 'EXTEND'",
    section: 'probation',
    flowsUsedIn: ['probation'],
  },
  {
    id: 'extendedRetirementDate',
    brdRow: 117,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EXTENED_RETIREMENT_DATE',
    labelTh: 'วันที่ขยายการเกษียณ',
    labelEn: 'Extended Retirement Date',
    type: 'date',
    required: false,
    section: 'probation',
    flowsUsedIn: ['empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: termination — BRD #111-114, #116 + EC_EMP_EMPLOYMENT_TERMINATION
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'resignedDate',
    brdRow: 111,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'EFFECTIVE_END_DATE',
    labelTh: 'วันที่ลาออก',
    labelEn: 'Resigned Date',
    type: 'date',
    required: true,
    section: 'termination',
    flowsUsedIn: ['terminate'],
  },
  {
    id: 'lastDateWorked',
    brdRow: 111,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'LAST_DATE_WORKED',
    labelTh: 'วันสุดท้ายที่ทำงาน',
    labelEn: 'Last Date Worked',
    type: 'date',
    required: true,
    section: 'termination',
    flowsUsedIn: ['terminate'],
  },
  {
    id: 'reasonForTermination',
    brdRow: 113,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'REASON_FOR_TERMINATION',
    labelTh: 'เหตุผลการลาออก',
    labelEn: 'Reason for Termination',
    type: 'picklist',
    required: true,
    picklistId: 'TERMINATION_REASON',
    maxLength: 256,
    section: 'termination',
    flowsUsedIn: ['terminate'],
  },
  {
    id: 'terminateVoluntaryInvoluntary',
    brdRow: 113,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'TERMINATE_VOLUNTARY_INVOLUNTARY',
    labelTh: 'ประเภทการลาออก (สมัครใจ/ไม่สมัครใจ)',
    labelEn: 'Terminate Voluntary / Involuntary',
    type: 'picklist',
    required: true,
    picklistId: 'VOLUNTARY',
    maxLength: 256,
    section: 'termination',
    flowsUsedIn: ['terminate'],
  },
  {
    id: 'okToRehire',
    brdRow: 114,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'OK_TO_REHIRE',
    labelTh: 'อนุญาตให้กลับเข้าทำงานซ้ำ',
    labelEn: 'OK to Rehire',
    type: 'boolean',
    required: true,
    defaultValue: true,
    readOnly: { role: ['Employee', 'Manager'] },
    section: 'termination',
    flowsUsedIn: ['terminate'],
  },
  {
    id: 'transferOutTo',
    brdRow: 110,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'TRANSFER_OUT_TO',
    labelTh: 'โอนย้ายออกไปที่',
    labelEn: 'Transfer Out To',
    type: 'picklist',
    required: false,
    picklistId: 'TRANSFER_OUT',
    maxLength: 256,
    visibleWhen: "reasonForTermination === 'TRANSFER'",
    section: 'termination',
    flowsUsedIn: ['terminate', 'transfer'],
  },
  {
    id: 'terminationAdditionalInformation',
    brdRow: 111,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'ADDITIONAL_INFORMATION_TERMINATION',
    labelTh: 'หมายเหตุเพิ่มเติม (การลาออก)',
    labelEn: 'Additional Information (Termination)',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'termination',
    flowsUsedIn: ['terminate'],
  },
  {
    id: 'terminationAttachment',
    brdRow: 112,
    sfEntity: 'EC_EMP_EMPLOYMENT_TERMINATION',
    sfField: 'ATTACHMENT_ID',
    labelTh: 'ไฟล์แนบเอกสารการลาออก',
    labelEn: 'Termination Attachment',
    type: 'string',
    required: false,
    section: 'termination',
    flowsUsedIn: ['terminate'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: transfer — BRD #110 Transfer Flow + EC_EMP_JOB transfer columns
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'transferFrom',
    brdRow: 110,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'TRANSFER_FROM',
    labelTh: 'โอนย้ายมาจาก',
    labelEn: 'Transfer From',
    type: 'picklist',
    required: true,
    picklistId: 'TRANSFER_FROM',
    maxLength: 256,
    section: 'transfer',
    flowsUsedIn: ['transfer'],
  },
  {
    id: 'transferJobEffectiveDate',
    brdRow: 110,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'OVERRIDE_CURRENT_JOB_EFFECTIVE_DATE',
    labelTh: 'วันที่ตำแหน่งใหม่มีผล',
    labelEn: 'New Job Effective Date',
    type: 'date',
    required: true,
    section: 'transfer',
    flowsUsedIn: ['transfer'],
  },
  {
    id: 'transferBusinessUnitEffectiveDate',
    brdRow: 110,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'OVERRIDE_CURRENT_BUSINESS_UNIT_EFFECTIVE_DATE',
    labelTh: 'วันที่ Business Unit ใหม่มีผล',
    labelEn: 'New Business Unit Effective Date',
    type: 'date',
    required: false,
    section: 'transfer',
    flowsUsedIn: ['transfer'],
  },
  {
    id: 'transferStoreBranchEffectiveDate',
    brdRow: 110,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'OVERRIDE_CURRENT_STORE_BRANCH_EFFECTIVE_DATE',
    labelTh: 'วันที่สาขาใหม่มีผล',
    labelEn: 'New Store / Branch Effective Date',
    type: 'date',
    required: false,
    section: 'transfer',
    flowsUsedIn: ['transfer'],
  },
  {
    id: 'transferCorporateTitleEffectiveDate',
    brdRow: 110,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'OVERRIDE_CURRENT_CORPORATE_TITLE_EFFECTIVE_DATE',
    labelTh: 'วันที่ Corporate Title ใหม่มีผล',
    labelEn: 'New Corporate Title Effective Date',
    type: 'date',
    required: false,
    section: 'transfer',
    flowsUsedIn: ['transfer'],
  },
  {
    id: 'transferJobGradeEffectiveDate',
    brdRow: 110,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'OVERRIDE_CURRENT_JG_EFFECTIVE_DATE',
    labelTh: 'วันที่ JG ใหม่มีผล',
    labelEn: 'New Job Grade Effective Date',
    type: 'date',
    required: false,
    section: 'transfer',
    flowsUsedIn: ['transfer'],
  },
  {
    id: 'transferPayGradeEffectiveDate',
    brdRow: 110,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'OVERRIDE_CURRENT_PG_EFFECTIVE_DATE',
    labelTh: 'วันที่ PG ใหม่มีผล',
    labelEn: 'New Pay Grade Effective Date',
    type: 'date',
    required: false,
    section: 'transfer',
    flowsUsedIn: ['transfer'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: rehire — BRD #102 Re-Hiring + EC_EMP_EMPLOYMENT.ORIGINAL_START_DATE
  //                                      + EC_EMP_JOB seniority flags
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'rehireOriginalStartDate',
    brdRow: 102,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'ORIGINAL_START_DATE',
    labelTh: 'วันเริ่มงานครั้งแรก (ก่อน Rehire)',
    labelEn: 'Original Hire Date',
    type: 'date',
    required: true,
    section: 'rehire',
    flowsUsedIn: ['rehire'],
  },
  {
    id: 'rehireKeepSeniority',
    brdRow: 102,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'SENIORITY_DATE',
    labelTh: 'นับอายุงานต่อเนื่องจากเดิม',
    labelEn: 'Keep Previous Seniority',
    type: 'boolean',
    required: true,
    defaultValue: false,
    section: 'rehire',
    flowsUsedIn: ['rehire'],
  },
  {
    id: 'rehirePreviousEmployeeId',
    brdRow: 102,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'CG_PREVIOUS_EMPLOYEE_ID',
    labelTh: 'รหัสพนักงานเดิม',
    labelEn: 'Previous Employee ID',
    type: 'string',
    required: true,
    maxLength: 256,
    section: 'rehire',
    flowsUsedIn: ['rehire'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: payment — BRD #118 Payment Information + PaymentInformationV3
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'paymentEffectiveStartDate',
    brdRow: 118,
    sfEntity: 'PaymentInformationV3',
    sfField: 'effectiveStartDate',
    labelTh: 'วันที่ข้อมูลการจ่ายเงินมีผล',
    labelEn: 'Payment Effective Start Date',
    type: 'date',
    required: true,
    section: 'payment',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'paymentJobCountry',
    brdRow: 118,
    sfEntity: 'PaymentInformationV3',
    sfField: 'jobCountry',
    labelTh: 'ประเทศที่จ่ายเงิน',
    labelEn: 'Job Country / Region',
    type: 'picklist',
    required: true,
    picklistId: 'FOTerritory',
    defaultValue: 'THA',
    section: 'payment',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: bankAccount — BRD #118 Payment Detail + PaymentInformationDetailV3
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'paymentMethod',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'paymentMethod',
    labelTh: 'วิธีการจ่ายเงิน',
    labelEn: 'Payment Method',
    type: 'picklist',
    required: true,
    picklistId: 'PaymentMethod',
    defaultValue: 'BANK_TRANSFER',
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'payType',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'payType',
    labelTh: 'ประเภทการจ่ายเงิน',
    labelEn: 'Pay Type',
    type: 'picklist',
    required: true,
    picklistId: 'PayType',
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'bankName',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'bank',
    labelTh: 'ธนาคาร',
    labelEn: 'Bank',
    type: 'picklist',
    required: true,
    picklistId: 'Bank',
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'bankAccountNumber',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'accountNumber',
    labelTh: 'เลขที่บัญชีธนาคาร',
    labelEn: 'Bank Account Number',
    type: 'string',
    required: true,
    maxLength: 64,
    regex: '^[0-9\\-]+$',
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'bankAccountOwner',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'accountOwner',
    labelTh: 'ชื่อเจ้าของบัญชี',
    labelEn: 'Account Owner',
    type: 'string',
    required: true,
    maxLength: 256,
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'bankCountry',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'bankCountry',
    labelTh: 'ประเทศของธนาคาร',
    labelEn: 'Bank Country / Region',
    type: 'picklist',
    required: true,
    picklistId: 'FOTerritory',
    defaultValue: 'THA',
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'paymentAmount',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'amount',
    labelTh: 'จำนวนเงิน',
    labelEn: 'Amount',
    type: 'number',
    required: false,
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'paymentPercent',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'percent',
    labelTh: 'สัดส่วนร้อยละ',
    labelEn: 'Percent',
    type: 'number',
    required: false,
    defaultValue: 100,
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'paymentCurrency',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'currency',
    labelTh: 'สกุลเงิน',
    labelEn: 'Currency',
    type: 'picklist',
    required: true,
    picklistId: 'Currency',
    defaultValue: 'THB',
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'paySequence',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'paySequence',
    labelTh: 'ลำดับการจ่าย',
    labelEn: 'Pay Sequence',
    type: 'number',
    required: false,
    defaultValue: 1,
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'paymentPurpose',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'purpose',
    labelTh: 'วัตถุประสงค์การจ่าย',
    labelEn: 'Purpose',
    type: 'string',
    required: false,
    maxLength: 256,
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'paymentRoutingNumber',
    brdRow: 118,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'routingNumber',
    labelTh: 'รหัส Sort Code / Routing',
    labelEn: 'Sort Code / Routing Number',
    type: 'string',
    required: false,
    maxLength: 64,
    section: 'bankAccount',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: compensation — BRD #119 Payroll + #120 Salary Base +
  //                          PaymentInformationDetailV3.customPayType
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'baseSalary',
    brdRow: 120,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'amount',
    labelTh: 'เงินเดือนพื้นฐาน',
    labelEn: 'Base Salary',
    type: 'number',
    required: true,
    readOnly: { role: ['Employee', 'Manager'] },
    section: 'compensation',
    flowsUsedIn: ['hire', 'rehire', 'transfer'],
  },
  {
    id: 'baseSalaryCurrency',
    brdRow: 120,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'currency',
    labelTh: 'สกุลเงินของเงินเดือน',
    labelEn: 'Base Salary Currency',
    type: 'picklist',
    required: true,
    picklistId: 'Currency',
    defaultValue: 'THB',
    section: 'compensation',
    flowsUsedIn: ['hire', 'rehire', 'transfer'],
  },
  {
    id: 'customPayType',
    brdRow: 119,
    sfEntity: 'PaymentInformationDetailV3',
    sfField: 'customPayType',
    labelTh: 'Pay Component พิเศษ',
    labelEn: 'Customised Pay Type',
    type: 'picklist',
    required: false,
    picklistId: 'CustomPayType',
    section: 'compensation',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'payScaleType',
    brdRow: 120,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'PAY_SCALE_TYPE_ID',
    labelTh: 'ประเภทฐานเงินเดือน',
    labelEn: 'Pay Scale Type',
    type: 'picklist',
    required: false,
    picklistId: 'ECPayScaleType',
    section: 'compensation',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'payScaleArea',
    brdRow: 120,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'PAY_SCALE_AREA_ID',
    labelTh: 'พื้นที่ฐานเงินเดือน',
    labelEn: 'Pay Scale Area',
    type: 'picklist',
    required: false,
    picklistId: 'ECPayScaleArea',
    section: 'compensation',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'payScaleGroup',
    brdRow: 120,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'PAY_SCALE_GROUP_ID',
    labelTh: 'กลุ่มฐานเงินเดือน',
    labelEn: 'Pay Scale Group',
    type: 'picklist',
    required: false,
    picklistId: 'ECPayScaleGroup',
    section: 'compensation',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
  {
    id: 'payScaleLevel',
    brdRow: 120,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'PAY_SCALE_LEVEL_ID',
    labelTh: 'ระดับฐานเงินเดือน',
    labelEn: 'Pay Scale Level',
    type: 'picklist',
    required: false,
    picklistId: 'ECPayScaleLevel',
    section: 'compensation',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: contractRenewal — BRD #115 Auto-Terminate Contract Employee
  // Fields reused from job section but surfaced under a renewal-specific section
  // via `flowsUsedIn: ['contractRenewal']` and dedicated ids for clarity.
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'contractRenewalEndDate',
    brdRow: 115,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'CONTRACT_END_DATE',
    labelTh: 'วันที่สิ้นสุดสัญญา (ต่ออายุ)',
    labelEn: 'Contract End Date (Renewal)',
    type: 'date',
    required: true,
    section: 'contractRenewal',
    flowsUsedIn: ['contractRenewal'],
  },
  {
    id: 'contractRenewalType',
    brdRow: 115,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'CONTRACT_TYPE',
    labelTh: 'ประเภทสัญญาใหม่',
    labelEn: 'Renewal Contract Type',
    type: 'picklist',
    required: true,
    picklistId: 'CONTRACT_TYPE',
    maxLength: 256,
    section: 'contractRenewal',
    flowsUsedIn: ['contractRenewal'],
  },
  {
    id: 'contractRenewalEventDate',
    brdRow: 115,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EFFECTIVE_START_DATE',
    labelTh: 'วันที่การต่ออายุสัญญามีผล',
    labelEn: 'Renewal Effective Date',
    type: 'date',
    required: true,
    section: 'contractRenewal',
    flowsUsedIn: ['contractRenewal'],
  },
  {
    id: 'contractRenewalAttachment',
    brdRow: 115,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'ATTACHMENT_ID',
    labelTh: 'ไฟล์แนบสัญญาใหม่',
    labelEn: 'Renewal Contract Attachment',
    type: 'string',
    required: false,
    section: 'contractRenewal',
    flowsUsedIn: ['contractRenewal'],
  },

  // ───────────────────────────────────────────────────────────────────────
  // SECTION: employmentInfo — miscellaneous employmentInfo-grouped fields
  // surfaced primarily in My Profile (empData) read-only view.
  // BRD #93 Age, #86 Year of Service, #23 Emp Job Info.
  // ───────────────────────────────────────────────────────────────────────
  {
    id: 'isConcurrentEmployment',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'IS_CONCURRENT_EMPLOYMENT',
    labelTh: 'การจ้างงานพร้อมกันหลายตำแหน่ง',
    labelEn: 'Is Concurrent Employment',
    type: 'picklist',
    required: false,
    picklistId: 'YES_NO',
    maxLength: 256,
    section: 'employmentInfo',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'effectiveLatestChange',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'EFFECTIVE_LATEST_CHANGE',
    labelTh: 'เป็นการเปลี่ยนแปลงล่าสุดที่มีผล',
    labelEn: 'Is Latest Effective Change',
    type: 'boolean',
    required: false,
    readOnly: {},
    section: 'employmentInfo',
    flowsUsedIn: ['empData'],
  },
  {
    id: 'hiringNotCompleted',
    brdRow: 109,
    sfEntity: 'EC_EMP_EMPLOYMENT',
    sfField: 'HIRING_NOT_COMPLETED',
    labelTh: 'การจ้างงานยังไม่สมบูรณ์',
    labelEn: 'Hiring Not Completed',
    type: 'boolean',
    required: false,
    readOnly: {},
    section: 'employmentInfo',
    flowsUsedIn: ['hire', 'empData'],
  },
  {
    id: 'timeZone',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'TIMEZONE',
    labelTh: 'เขตเวลา',
    labelEn: 'Time Zone',
    type: 'string',
    required: false,
    maxLength: 128,
    defaultValue: 'Asia/Bangkok',
    section: 'employmentInfo',
    flowsUsedIn: ['hire', 'rehire', 'empData'],
  },
  {
    id: 'pointOfSales',
    brdRow: 23,
    sfEntity: 'EC_EMP_JOB',
    sfField: 'POINT_OF_SALES',
    labelTh: 'Point of Sales',
    labelEn: 'Point of Sales',
    type: 'picklist',
    required: false,
    picklistId: 'POINT_OF_SALES',
    maxLength: 256,
    section: 'employmentInfo',
    flowsUsedIn: ['hire', 'rehire', 'transfer', 'empData'],
  },
];

// Freeze to guarantee downstream consumers cannot mutate the source of truth.
Object.freeze(EC_CORE_FIELDS);
